//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Iletisim Formlari</summary>
	[PublishedContentModel("iletisimFormlari")]
	public partial class IletisimFormlari : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "iletisimFormlari";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public IletisimFormlari(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<IletisimFormlari, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// CinsiyetSecimi
		///</summary>
		[ImplementPropertyType("cinsiyetSecimi")]
		public string CinsiyetSecimi
		{
			get { return this.GetPropertyValue<string>("cinsiyetSecimi"); }
		}

		///<summary>
		/// Email From
		///</summary>
		[ImplementPropertyType("emailFrom")]
		public string EmailFrom
		{
			get { return this.GetPropertyValue<string>("emailFrom"); }
		}

		///<summary>
		/// Message
		///</summary>
		[ImplementPropertyType("message")]
		public string Message
		{
			get { return this.GetPropertyValue<string>("message"); }
		}

		///<summary>
		/// Name From
		///</summary>
		[ImplementPropertyType("nameFrom")]
		public string NameFrom
		{
			get { return this.GetPropertyValue<string>("nameFrom"); }
		}

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("phone")]
		public string Phone
		{
			get { return this.GetPropertyValue<string>("phone"); }
		}

		///<summary>
		/// Surname From
		///</summary>
		[ImplementPropertyType("surnameFrom")]
		public string SurnameFrom
		{
			get { return this.GetPropertyValue<string>("surnameFrom"); }
		}
	}
}
